/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ContactImport } from './routes/contact'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as AppLayoutImport } from './routes/app/_layout'
import { Route as AppLayoutAuthenticatedImport } from './routes/app/_layout/_authenticated'
import { Route as AppLayoutAuthenticatedIndexImport } from './routes/app/_layout/_authenticated/index'
import { Route as AppLayoutAuthSignInImport } from './routes/app/_layout/auth/sign-in'
import { Route as AppLayoutAuthenticatedIncomeImport } from './routes/app/_layout/_authenticated/income'
import { Route as AppLayoutAuthenticatedHierarchyImport } from './routes/app/_layout/_authenticated/hierarchy'
import { Route as AppLayoutAuthenticatedFinanceChartsImport } from './routes/app/_layout/_authenticated/finance-charts'
import { Route as AppLayoutAuthenticatedExpenseImport } from './routes/app/_layout/_authenticated/expense'
import { Route as AppLayoutAuthenticatedAnnualLeaveImport } from './routes/app/_layout/_authenticated/annual-leave'
import { Route as AppLayoutAuthenticatedStaffIndexImport } from './routes/app/_layout/_authenticated/staff/index'
import { Route as AppLayoutAuthenticatedStaffStaffRequestsImport } from './routes/app/_layout/_authenticated/staff/staff-requests'
import { Route as AppLayoutAuthenticatedStaffAddNewImport } from './routes/app/_layout/_authenticated/staff/add-new'
import { Route as AppLayoutAuthenticatedStaffStaffIdIndexImport } from './routes/app/_layout/_authenticated/staff/$staffId/index'
import { Route as AppLayoutAuthenticatedStaffUpdateStaffIdIndexImport } from './routes/app/_layout/_authenticated/staff/update/$staffId/index'

// Create Virtual Routes

const AppImport = createFileRoute('/app')()

// Create/Update Routes

const AppRoute = AppImport.update({
  path: '/app',
  getParentRoute: () => rootRoute,
} as any)

const ContactRoute = ContactImport.update({
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppLayoutRoute = AppLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => AppRoute,
} as any)

const AppLayoutAuthenticatedRoute = AppLayoutAuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => AppLayoutRoute,
} as any)

const AppLayoutAuthenticatedIndexRoute =
  AppLayoutAuthenticatedIndexImport.update({
    path: '/',
    getParentRoute: () => AppLayoutAuthenticatedRoute,
  } as any)

const AppLayoutAuthSignInRoute = AppLayoutAuthSignInImport.update({
  path: '/auth/sign-in',
  getParentRoute: () => AppLayoutRoute,
} as any)

const AppLayoutAuthenticatedIncomeRoute =
  AppLayoutAuthenticatedIncomeImport.update({
    path: '/income',
    getParentRoute: () => AppLayoutAuthenticatedRoute,
  } as any)

const AppLayoutAuthenticatedHierarchyRoute =
  AppLayoutAuthenticatedHierarchyImport.update({
    path: '/hierarchy',
    getParentRoute: () => AppLayoutAuthenticatedRoute,
  } as any)

const AppLayoutAuthenticatedFinanceChartsRoute =
  AppLayoutAuthenticatedFinanceChartsImport.update({
    path: '/finance-charts',
    getParentRoute: () => AppLayoutAuthenticatedRoute,
  } as any)

const AppLayoutAuthenticatedExpenseRoute =
  AppLayoutAuthenticatedExpenseImport.update({
    path: '/expense',
    getParentRoute: () => AppLayoutAuthenticatedRoute,
  } as any)

const AppLayoutAuthenticatedAnnualLeaveRoute =
  AppLayoutAuthenticatedAnnualLeaveImport.update({
    path: '/annual-leave',
    getParentRoute: () => AppLayoutAuthenticatedRoute,
  } as any)

const AppLayoutAuthenticatedStaffIndexRoute =
  AppLayoutAuthenticatedStaffIndexImport.update({
    path: '/staff/',
    getParentRoute: () => AppLayoutAuthenticatedRoute,
  } as any)

const AppLayoutAuthenticatedStaffStaffRequestsRoute =
  AppLayoutAuthenticatedStaffStaffRequestsImport.update({
    path: '/staff/staff-requests',
    getParentRoute: () => AppLayoutAuthenticatedRoute,
  } as any)

const AppLayoutAuthenticatedStaffAddNewRoute =
  AppLayoutAuthenticatedStaffAddNewImport.update({
    path: '/staff/add-new',
    getParentRoute: () => AppLayoutAuthenticatedRoute,
  } as any)

const AppLayoutAuthenticatedStaffStaffIdIndexRoute =
  AppLayoutAuthenticatedStaffStaffIdIndexImport.update({
    path: '/staff/$staffId/',
    getParentRoute: () => AppLayoutAuthenticatedRoute,
  } as any)

const AppLayoutAuthenticatedStaffUpdateStaffIdIndexRoute =
  AppLayoutAuthenticatedStaffUpdateStaffIdIndexImport.update({
    path: '/staff/update/$staffId/',
    getParentRoute: () => AppLayoutAuthenticatedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/contact': {
      preLoaderRoute: typeof ContactImport
      parentRoute: typeof rootRoute
    }
    '/app': {
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/app/_layout': {
      preLoaderRoute: typeof AppLayoutImport
      parentRoute: typeof AppRoute
    }
    '/app/_layout/_authenticated': {
      preLoaderRoute: typeof AppLayoutAuthenticatedImport
      parentRoute: typeof AppLayoutImport
    }
    '/app/_layout/_authenticated/annual-leave': {
      preLoaderRoute: typeof AppLayoutAuthenticatedAnnualLeaveImport
      parentRoute: typeof AppLayoutAuthenticatedImport
    }
    '/app/_layout/_authenticated/expense': {
      preLoaderRoute: typeof AppLayoutAuthenticatedExpenseImport
      parentRoute: typeof AppLayoutAuthenticatedImport
    }
    '/app/_layout/_authenticated/finance-charts': {
      preLoaderRoute: typeof AppLayoutAuthenticatedFinanceChartsImport
      parentRoute: typeof AppLayoutAuthenticatedImport
    }
    '/app/_layout/_authenticated/hierarchy': {
      preLoaderRoute: typeof AppLayoutAuthenticatedHierarchyImport
      parentRoute: typeof AppLayoutAuthenticatedImport
    }
    '/app/_layout/_authenticated/income': {
      preLoaderRoute: typeof AppLayoutAuthenticatedIncomeImport
      parentRoute: typeof AppLayoutAuthenticatedImport
    }
    '/app/_layout/auth/sign-in': {
      preLoaderRoute: typeof AppLayoutAuthSignInImport
      parentRoute: typeof AppLayoutImport
    }
    '/app/_layout/_authenticated/': {
      preLoaderRoute: typeof AppLayoutAuthenticatedIndexImport
      parentRoute: typeof AppLayoutAuthenticatedImport
    }
    '/app/_layout/_authenticated/staff/add-new': {
      preLoaderRoute: typeof AppLayoutAuthenticatedStaffAddNewImport
      parentRoute: typeof AppLayoutAuthenticatedImport
    }
    '/app/_layout/_authenticated/staff/staff-requests': {
      preLoaderRoute: typeof AppLayoutAuthenticatedStaffStaffRequestsImport
      parentRoute: typeof AppLayoutAuthenticatedImport
    }
    '/app/_layout/_authenticated/staff/': {
      preLoaderRoute: typeof AppLayoutAuthenticatedStaffIndexImport
      parentRoute: typeof AppLayoutAuthenticatedImport
    }
    '/app/_layout/_authenticated/staff/$staffId/': {
      preLoaderRoute: typeof AppLayoutAuthenticatedStaffStaffIdIndexImport
      parentRoute: typeof AppLayoutAuthenticatedImport
    }
    '/app/_layout/_authenticated/staff/update/$staffId/': {
      preLoaderRoute: typeof AppLayoutAuthenticatedStaffUpdateStaffIdIndexImport
      parentRoute: typeof AppLayoutAuthenticatedImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AboutRoute,
  ContactRoute,
  AppRoute.addChildren([
    AppLayoutRoute.addChildren([
      AppLayoutAuthenticatedRoute.addChildren([
        AppLayoutAuthenticatedAnnualLeaveRoute,
        AppLayoutAuthenticatedExpenseRoute,
        AppLayoutAuthenticatedFinanceChartsRoute,
        AppLayoutAuthenticatedHierarchyRoute,
        AppLayoutAuthenticatedIncomeRoute,
        AppLayoutAuthenticatedIndexRoute,
        AppLayoutAuthenticatedStaffAddNewRoute,
        AppLayoutAuthenticatedStaffStaffRequestsRoute,
        AppLayoutAuthenticatedStaffIndexRoute,
        AppLayoutAuthenticatedStaffStaffIdIndexRoute,
        AppLayoutAuthenticatedStaffUpdateStaffIdIndexRoute,
      ]),
      AppLayoutAuthSignInRoute,
    ]),
  ]),
])

/* prettier-ignore-end */
