/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutAuthenticatedImport } from './routes/_layout/_authenticated'
import { Route as LayoutAuthenticatedIndexImport } from './routes/_layout/_authenticated/index'
import { Route as LayoutAuthSignInImport } from './routes/_layout/auth/sign-in'
import { Route as LayoutAuthenticatedIncomeImport } from './routes/_layout/_authenticated/income'
import { Route as LayoutAuthenticatedHierarchyImport } from './routes/_layout/_authenticated/hierarchy'
import { Route as LayoutAuthenticatedFinanceChartsImport } from './routes/_layout/_authenticated/finance-charts'
import { Route as LayoutAuthenticatedExpenseImport } from './routes/_layout/_authenticated/expense'
import { Route as LayoutAuthenticatedAnnualLeaveImport } from './routes/_layout/_authenticated/annual-leave'
import { Route as LayoutAuthenticatedStaffIndexImport } from './routes/_layout/_authenticated/staff/index'
import { Route as LayoutAuthenticatedStaffStaffRequestsImport } from './routes/_layout/_authenticated/staff/staff-requests'
import { Route as LayoutAuthenticatedStaffAddNewImport } from './routes/_layout/_authenticated/staff/add-new'
import { Route as LayoutAuthenticatedStaffStaffIdIndexImport } from './routes/_layout/_authenticated/staff/$staffId/index'
import { Route as LayoutAuthenticatedStaffUpdateStaffIdIndexImport } from './routes/_layout/_authenticated/staff/update/$staffId/index'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutAuthenticatedRoute = LayoutAuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAuthenticatedIndexRoute = LayoutAuthenticatedIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutAuthenticatedRoute,
} as any)

const LayoutAuthSignInRoute = LayoutAuthSignInImport.update({
  path: '/auth/sign-in',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAuthenticatedIncomeRoute = LayoutAuthenticatedIncomeImport.update({
  path: '/income',
  getParentRoute: () => LayoutAuthenticatedRoute,
} as any)

const LayoutAuthenticatedHierarchyRoute =
  LayoutAuthenticatedHierarchyImport.update({
    path: '/hierarchy',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)

const LayoutAuthenticatedFinanceChartsRoute =
  LayoutAuthenticatedFinanceChartsImport.update({
    path: '/finance-charts',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)

const LayoutAuthenticatedExpenseRoute = LayoutAuthenticatedExpenseImport.update(
  {
    path: '/expense',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any,
)

const LayoutAuthenticatedAnnualLeaveRoute =
  LayoutAuthenticatedAnnualLeaveImport.update({
    path: '/annual-leave',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)

const LayoutAuthenticatedStaffIndexRoute =
  LayoutAuthenticatedStaffIndexImport.update({
    path: '/staff/',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)

const LayoutAuthenticatedStaffStaffRequestsRoute =
  LayoutAuthenticatedStaffStaffRequestsImport.update({
    path: '/staff/staff-requests',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)

const LayoutAuthenticatedStaffAddNewRoute =
  LayoutAuthenticatedStaffAddNewImport.update({
    path: '/staff/add-new',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)

const LayoutAuthenticatedStaffStaffIdIndexRoute =
  LayoutAuthenticatedStaffStaffIdIndexImport.update({
    path: '/staff/$staffId/',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)

const LayoutAuthenticatedStaffUpdateStaffIdIndexRoute =
  LayoutAuthenticatedStaffUpdateStaffIdIndexImport.update({
    path: '/staff/update/$staffId/',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/_authenticated': {
      preLoaderRoute: typeof LayoutAuthenticatedImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/_authenticated/annual-leave': {
      preLoaderRoute: typeof LayoutAuthenticatedAnnualLeaveImport
      parentRoute: typeof LayoutAuthenticatedImport
    }
    '/_layout/_authenticated/expense': {
      preLoaderRoute: typeof LayoutAuthenticatedExpenseImport
      parentRoute: typeof LayoutAuthenticatedImport
    }
    '/_layout/_authenticated/finance-charts': {
      preLoaderRoute: typeof LayoutAuthenticatedFinanceChartsImport
      parentRoute: typeof LayoutAuthenticatedImport
    }
    '/_layout/_authenticated/hierarchy': {
      preLoaderRoute: typeof LayoutAuthenticatedHierarchyImport
      parentRoute: typeof LayoutAuthenticatedImport
    }
    '/_layout/_authenticated/income': {
      preLoaderRoute: typeof LayoutAuthenticatedIncomeImport
      parentRoute: typeof LayoutAuthenticatedImport
    }
    '/_layout/auth/sign-in': {
      preLoaderRoute: typeof LayoutAuthSignInImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/_authenticated/': {
      preLoaderRoute: typeof LayoutAuthenticatedIndexImport
      parentRoute: typeof LayoutAuthenticatedImport
    }
    '/_layout/_authenticated/staff/add-new': {
      preLoaderRoute: typeof LayoutAuthenticatedStaffAddNewImport
      parentRoute: typeof LayoutAuthenticatedImport
    }
    '/_layout/_authenticated/staff/staff-requests': {
      preLoaderRoute: typeof LayoutAuthenticatedStaffStaffRequestsImport
      parentRoute: typeof LayoutAuthenticatedImport
    }
    '/_layout/_authenticated/staff/': {
      preLoaderRoute: typeof LayoutAuthenticatedStaffIndexImport
      parentRoute: typeof LayoutAuthenticatedImport
    }
    '/_layout/_authenticated/staff/$staffId/': {
      preLoaderRoute: typeof LayoutAuthenticatedStaffStaffIdIndexImport
      parentRoute: typeof LayoutAuthenticatedImport
    }
    '/_layout/_authenticated/staff/update/$staffId/': {
      preLoaderRoute: typeof LayoutAuthenticatedStaffUpdateStaffIdIndexImport
      parentRoute: typeof LayoutAuthenticatedImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([
    LayoutAuthenticatedRoute.addChildren([
      LayoutAuthenticatedAnnualLeaveRoute,
      LayoutAuthenticatedExpenseRoute,
      LayoutAuthenticatedFinanceChartsRoute,
      LayoutAuthenticatedHierarchyRoute,
      LayoutAuthenticatedIncomeRoute,
      LayoutAuthenticatedIndexRoute,
      LayoutAuthenticatedStaffAddNewRoute,
      LayoutAuthenticatedStaffStaffRequestsRoute,
      LayoutAuthenticatedStaffIndexRoute,
      LayoutAuthenticatedStaffStaffIdIndexRoute,
      LayoutAuthenticatedStaffUpdateStaffIdIndexRoute,
    ]),
    LayoutAuthSignInRoute,
  ]),
])

/* prettier-ignore-end */
